"""PDF exporter — renders career coach output as a professional PDF resume.

Uses fpdf2 with system CJK fonts for Chinese text.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from loguru import logger


def export_resume_pdf(state: dict[str, Any], output_path: str) -> str:
    """Export the optimized resume as a PDF with Chinese font support."""
    try:
        from fpdf import FPDF
    except ImportError:
        raise ImportError("需要安装 fpdf2。运行: pip install fpdf2")

    arch = state.get("architecture", {})
    if not arch:
        raise ValueError("没有可导出的简历内容")

    font_path = _find_cjk_font()
    if not font_path:
        raise RuntimeError("系统未找到中文字体（msyh/simsun/simhei），无法生成 PDF。Markdown 文件仍可正常导出。")

    pdf = FPDF()
    pdf.set_left_margin(15)
    pdf.set_right_margin(15)
    pdf.add_page()
    pdf.add_font("CJK", "", font_path)

    try:
        _write_title(pdf, "个人简历")

        summary = arch.get("personal_summary", "")
        if summary:
            _write_heading(pdf, "个人摘要")
            _write_body(pdf, summary)

        skills = arch.get("skills_matrix", "")
        if skills:
            _write_heading(pdf, "专业技能")
            _write_body(pdf, skills)

        experience = arch.get("work_experience", "")
        if experience:
            _write_heading(pdf, "工作 / 项目经历")
            _write_body(pdf, experience)


        highlights = arch.get("additional_highlights", "")
        if highlights:
            _write_heading(pdf, "附加亮点")
            _write_body(pdf, highlights)

        pdf.ln(6)
        pdf.set_font("Helvetica", size=7)
        gen_time = datetime.now().strftime("%Y-%m-%d %H:%M")
        pdf.cell(0, 5, f"Generated by CareerCraft | {gen_time}", align="C")

        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        pdf.output(output_path)
        logger.info(f"PDF exported: {output_path}")
        return output_path

    except Exception as e:
        raise RuntimeError(f"PDF 生成失败: {e}") from e


def _find_cjk_font() -> str | None:
    """Find an available CJK font on the system."""
    import platform

    paths = []
    if platform.system() == "Windows":
        paths = [
            "C:/Windows/Fonts/msyh.ttc",
            "C:/Windows/Fonts/simhei.ttf",
            "C:/Windows/Fonts/simsun.ttc",
        ]
    elif platform.system() == "Darwin":
        paths = [
            "/System/Library/Fonts/PingFang.ttc",
            "/Library/Fonts/Arial Unicode.ttf",
        ]
    else:
        paths = ["/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc"]

    for fp in paths:
        if Path(fp).exists():
            logger.info(f"Using CJK font: {fp}")
            return fp
    return None


def _write_title(pdf: Any, title: str) -> None:
    pdf.set_font("CJK", size=16)
    pdf.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
    y = pdf.get_y()
    pdf.line(15, y + 2, pdf.w - 15, y + 2)
    pdf.ln(6)


def _write_heading(pdf: Any, title: str) -> None:
    pdf.set_font("CJK", size=12)
    y0 = pdf.get_y()
    pdf.cell(0, 7, title, new_x="LMARGIN", new_y="NEXT")
    y1 = pdf.get_y()
    pdf.line(15, y1, pdf.w - 15, y1)
    pdf.ln(3)


def _write_body(pdf: Any, text: str) -> None:
    pdf.set_font("CJK", size=10)
    # Strip markdown syntax
    for ch in ["**", "__", "`", "```", "### ", "## ", "# "]:
        text = text.replace(ch, "")
    # Cap long lines that break fpdf2
    lines = []
    for line in text.split("\n"):
        line = line.strip()
        if len(line) > 200:
            line = line[:200] + "..."
        lines.append(line)
    text = "\n".join(lines)

    try:
        pdf.multi_cell(w=0, h=5.5, text=text)
    except Exception:
        # Last resort: strip non-ASCII
        safe = text.encode("ascii", errors="ignore").decode("ascii").strip()
        if safe:
            pdf.set_font("Helvetica", size=8)
            pdf.multi_cell(w=0, h=5, text=safe)
            pdf.set_font("CJK", size=10)
